server:
  port: 8080
spring:
  application:
    name: libraryapi
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
#      ddl-auto: update
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      #hibernate.format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 580908614657-cq521ubmga8mo80aa77na9lq8mrrp7nm.apps.googleusercontent.com
            client-secret: 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
logging:
  level:
    net:
      ttddyy:
        dsproxy:
          listener: debug